name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    - name: Set Environment Variables
      run: echo "NEW_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV

    - name: Docker Login
      run: |
        echo "New version: $NEW_VERSION !!!!!!!!!!"
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t jhonomar/docker-graphql:$NEW_VERSION .
        docker build -t jhonomar/docker-graphql:latest .

    - name: List Docker Images (Debugging)
      run: docker images

    - name: Push Docker Image
      run: |
        docker push jhonomar/docker-graphql:$NEW_VERSION
        docker push jhonomar/docker-graphql:latest
