name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t jhonomar/docker-graphql:0.0.2 .

    - name: List Docker Images (Debugging)
      run: docker images

    - name: Push Docker Image
      run: docker push jhonomar/docker-graphql:0.0.2
